import os
import time
from contextlib import asynccontextmanager
from typing import Optional, Dict, Any, List
from pathlib import Path

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.predict import predictor
from src.config import MODELS_DIR
from src.gemini_service import gemini_service


# Pydantic Schemas for Request & Response validation
class PredictRequest(BaseModel):
    title: Optional[str] = Field(
        default="",
        description="Headline or title of the news article",
        examples=["Senate approves bipartisan clean energy infrastructure investment package"]
    )
    text: str = Field(
        ...,
        min_length=5,
        description="Full text body or excerpt of the news article",
        examples=["WASHINGTON (Reuters) - Lawmakers passed comprehensive legislation allocating billions to grid upgrades after committee debate."]
    )
    model: Optional[str] = Field(
        default=None,
        description="Optional model override: 'logistic_regression', 'naive_bayes', 'svm'",
        examples=["logistic_regression"]
    )
    dataset: Optional[str] = Field(
        default="isot",
        description="Dataset to use for prediction: 'isot' or 'liar'",
        examples=["isot"]
    )


class PredictResponse(BaseModel):
    prediction: str = Field(..., description="Binary classification outcome: 'FAKE' or 'REAL'")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model prediction confidence score")
    model: str = Field(..., description="Name of the active machine learning classifier")
    probabilities: Dict[str, float] = Field(..., description="Class probability distribution for FAKE and REAL")
    wordCount: int = Field(..., description="Total word count analyzed")
    charCount: int = Field(..., description="Total character count analyzed")
    topTokens: Optional[List[str]] = Field(default=[], description="Top salient TF-IDF vocabulary tokens")
    explanation: str = Field(..., description="Linguistic and stylistic rationale generated by classifier")
    geminiInsights: Optional[Dict[str, Any]] = Field(default=None, description="Real-time Gemini AI credibility analysis")


class HealthResponse(BaseModel):
    status: str
    service: str
    active_model: str
    uptime_seconds: float


start_time = time.time()


# Lifespan Context Manager to load artifacts ONCE on startup
@asynccontextmanager
async def lifespan(app: FastAPI):
    print("------------------------------------------------------------------")
    print("🚀 Initializing FastAPI NLP Prediction Microservice...")
    predictor.load_models("isot")
    predictor.load_models("liar")
    print("📦 Models loaded in memory")
    print("------------------------------------------------------------------")
    yield
    print("🛑 Shutting down ML Microservice...")


app = FastAPI(
    title="Fake News Detection NLP Microservice",
    description="High-performance FastAPI service providing NLP inference for news verification using Scikit-learn and TF-IDF.",
    version="1.0.0",
    lifespan=lifespan
)

# CORS Configuration allowing Node.js Express backend and Vite frontend
allowed_origins_env = os.getenv("ALLOWED_ORIGINS", "http://localhost:5000,http://localhost:5173,http://127.0.0.1:5000,http://127.0.0.1:5173")
origins = [o.strip() for o in allowed_origins_env.split(",") if o.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins if origins else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", response_model=HealthResponse, tags=["System"])
def get_health():
    """
    Returns microservice health, system uptime, and active model name.
    """
    return {
        "status": "ok",
        "service": "Fake News Detection NLP Microservice",
        "active_model": "multiple",
        "uptime_seconds": round(time.time() - start_time, 2)
    }


@app.get("/", tags=["System"])
def root():
    return {
        "name": "Fake News Detection NLP Microservice",
        "version": "1.0.0",
        "health": "/health",
        "docs": "/docs",
        "predict": "POST /predict"
    }


@app.post("/predict", response_model=PredictResponse, status_code=status.HTTP_200_OK, tags=["Inference"])
def predict_news(payload: PredictRequest):
    """
    Classify news article text into 'FAKE' or 'REAL' using the trained NLP model.
    Includes real-time Gemini AI credibility insights when API key is configured.
    """
    try:
        if not payload.text or len(payload.text.strip()) < 5:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Article text body must be at least 5 characters long."
            )

        result = predictor.predict(
            text=(payload.title or "") + " " + payload.text,
            model_name=payload.model,
            dataset=payload.dataset
        )
        combined_text = ((payload.title or "") + " " + payload.text).strip()
        result["wordCount"] = len(combined_text.split())
        result["charCount"] = len(combined_text)
        result["topTokens"] = []
        result["explanation"] = "Prediction generated by the selected trained model."
        
        # Enhance with Gemini AI insights
        gemini_insights = gemini_service.analyze_news_article(
            title=payload.title or "",
            text=payload.text,
            prediction=result["prediction"],
            confidence=result["confidence"]
        )
        result["geminiInsights"] = gemini_insights
        
        return result
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Inference error: {str(exc)}"
        )


@app.post("/predict/all", status_code=status.HTTP_200_OK, tags=["Inference"])
def predict_all_models(payload: PredictRequest):
    """
    Run full multi-model simulation across the four trained candidate models and 2 ensemble architectures.
    Includes real-time Gemini AI credibility insights when API key is configured.
    """
    try:
        if not payload.text or len(payload.text.strip()) < 5:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Article text body must be at least 5 characters long."
            )

        result = predictor.predict_all(
            text=payload.text,
            title=payload.title or "",
            dataset=payload.dataset
        )
        
        # Enhance with Gemini AI insights using soft ensemble prediction
        soft_ensemble = result.get("ensembles", {}).get("weighted_soft_ensemble", {})
        gemini_insights = gemini_service.analyze_news_article(
            title=payload.title or "",
            text=payload.text,
            prediction=soft_ensemble.get("prediction", "REAL"),
            confidence=soft_ensemble.get("confidence", 0.5)
        )
        result["geminiInsights"] = gemini_insights
        
        return result
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Multi-model simulation error: {str(exc)}"
        )


@app.get("/experiment-metadata", status_code=status.HTTP_200_OK, tags=["Experiments"])
def get_experiment_metadata(dataset: str = "isot"):
    """
    Returns full experimental dataset metrics, 5-fold CV scores, validation weights, and test benchmarks.
    """
    import json
    from src.config import RESULTS_DIR

    metadata_path = RESULTS_DIR / dataset / "benchmark.json"
    if not metadata_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Experiment metadata file for dataset {dataset} has not been generated yet."
        )
    with open(metadata_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("api.main:app", host="0.0.0.0", port=port, reload=True)
