import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, BookOpen, GitBranch, Cpu, ArrowUpRight } from 'lucide-react';

export const Footer = () => {
  return (
    <footer className="app-footer">
      <div className="footer-container">
        <div className="footer-top-grid">
          {/* Col 1: About Project */}
          <div className="footer-col footer-col-brand">
            <div className="footer-brand">
              <ShieldCheck className="footer-brand-icon" size={22} />
              <span className="footer-brand-title">VeriNews AI</span>
            </div>
            <p className="footer-description">
              An applied machine learning and natural language processing research system developed 
              to classify, evaluate, and interpret textual news authenticity in real-time.
            </p>
            <div className="footer-badge-pill">
              <Cpu size={14} />
              <span>TF-IDF &bull; Scikit-Learn &bull; D3.js</span>
            </div>
          </div>

          {/* Col 2: Navigation */}
          <div className="footer-col">
            <h4 className="footer-heading">Platform</h4>
            <ul className="footer-links">
              <li><Link to="/simulation">Simulation Lab</Link></li>
              <li><Link to="/experiments">Benchmark Matrix</Link></li>
              <li><Link to="/dashboard">Executive Dashboard</Link></li>
              <li><Link to="/analytics">Model Analytics</Link></li>
              <li><Link to="/history">Prediction History</Link></li>
            </ul>
          </div>

          {/* Col 3: Research Concepts */}
          <div className="footer-col">
            <h4 className="footer-heading">Research & Method</h4>
            <ul className="footer-links">
              <li><Link to="/about#tf-idf">TF-IDF Vectorization</Link></li>
              <li><Link to="/about#models">Passive-Aggressive Model</Link></li>
              <li><Link to="/about#pipeline">NLP Preprocessing Pipeline</Link></li>
              <li><Link to="/about#evaluation">Confusion Matrix & Metrics</Link></li>
            </ul>
          </div>

          {/* Col 4: Academic Note */}
          <div className="footer-col">
            <h4 className="footer-heading">Academic Project</h4>
            <p className="footer-note-text">
              Fake News Detection Using Machine Learning and Natural Language Processing.
            </p>
            <div className="academic-tag">
              <GitBranch size={14} />
              <span>Full-Stack MERN Architecture</span>
            </div>
          </div>
        </div>

        <div className="footer-bottom-bar">
          <div className="footer-disclaimer">
            Disclaimer: Predictions are generated by statistical machine learning models trained on benchmark linguistic corpora. Results reflect statistical probability and linguistic pattern correlation.
          </div>
          <div className="footer-copyright">
            &copy; {new Date().getFullYear()} Fake News Detection Research System. Academic Project.
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
